[package]
name = "boxfunge"
version = "0.2.0"
edition = "2021"

[dependencies]
argh = "0.1"
glam = "0.29"
rand = { version = "0.8", default-features = false, features = [
	"std",
	"small_rng",
] }
thiserror = "2"

[profile.release]
lto = "fat"
